# docker-compose testing

version: '3.8'

services:
  sarabi-frontend-dev:
    build:
      context: .
      target: build
    container_name: sarabi-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host
